name: Deploy to lambda
on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #       python-version: 3.9

    # - name: Install dependencies
    #   run: |
    #     python -m venv venv
    #     source venv/bin/activate
    #     pip install -r requirements.txt

    # pip install -r requirements.txt -t .
    # zip function.zip lambda_function.py
    # zip -r function.zip *

    - name: Package function
      run : |
          zip function.zip lambda_function.py

    - name: Check zip file
      run : ls -lrt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check credentials
      run : |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
    - name: Install AWS CLI
      run : sudo apt-get install awscli -y

    - name: Deploy to S3
      run : |
          aws s3 cp ./function.zip s3://resume-lambda-bucket --exclude ".git/*"

    # - name: Deploy Function
    #   uses: appleboy/lambda-action@master
    #   with:
    #       aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws_region: ${{ secrets.AWS_REGION }}
    #       function_name: CloudResumeLambda
    #       zip_file: function.zip